language: node_js
node_js:
    - "8"
    - "9"
    - "10"

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
before_install:
    - git clone --depth 1 https://github.com/arago/ogit $TRAVIS_BUILD_DIR/../OGIT
    - npm i -g yarn
