window.esdocSearchIndex = [
    [
        "hiro-graph-orm/lib/context/context_entity.doc~context$entity",
        "class/src/context/context_entity.doc.js~Context$Entity.html",
        '<span>Context$Entity</span> <span class="search-result-import-path">hiro-graph-orm/lib/context/context_entity.doc</span>',
        "class"
    ],
    [
        "hiro-graph-orm/lib/context~context",
        "class/src/context/index.js~Context.html",
        '<span>Context</span> <span class="search-result-import-path">hiro-graph-orm/lib/context</span>',
        "class"
    ],
    [
        "hiro-graph-orm/lib/vertex/graph~graphvertex",
        "class/src/vertex/graph.js~GraphVertex.html",
        '<span>GraphVertex</span> <span class="search-result-import-path">hiro-graph-orm/lib/vertex/graph</span>',
        "class"
    ],
    [
        "hiro-graph-orm/lib/gremlin~gremlinquerybuilder",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html",
        '<span>GremlinQueryBuilder</span> <span class="search-result-import-path">hiro-graph-orm/lib/gremlin</span>',
        "class"
    ],
    [
        "hiro-graph-orm/lib/schema~schema",
        "class/src/schema/index.js~Schema.html",
        '<span>Schema</span> <span class="search-result-import-path">hiro-graph-orm/lib/schema</span>',
        "class"
    ],
    [
        "hiro-graph-orm/lib/vertex~vertex",
        "class/src/vertex/index.js~Vertex.html",
        '<span>Vertex</span> <span class="search-result-import-path">hiro-graph-orm/lib/vertex</span>',
        "class"
    ],
    [
        "hiro-graph-orm/lib/codec/bool~createbool",
        "function/index.html#static-function-createBool",
        '<span>createBool</span> <span class="search-result-import-path">hiro-graph-orm/lib/codec/bool</span>',
        "function"
    ],
    [
        "hiro-graph-orm/lib/codec~createcodec",
        "function/index.html#static-function-createCodec",
        '<span>createCodec</span> <span class="search-result-import-path">hiro-graph-orm/lib/codec</span>',
        "function"
    ],
    [
        "hiro-graph-orm/lib/schema/entity~createentity",
        "function/index.html#static-function-createEntity",
        '<span>createEntity</span> <span class="search-result-import-path">hiro-graph-orm/lib/schema/entity</span>',
        "function"
    ],
    [
        "hiro-graph-orm/lib/codec/enum~createenum",
        "function/index.html#static-function-createEnum",
        '<span>createEnum</span> <span class="search-result-import-path">hiro-graph-orm/lib/codec/enum</span>',
        "function"
    ],
    [
        "hiro-graph-orm/lib/vertex/graph~createvertex",
        "function/index.html#static-function-createVertex",
        '<span>createVertex</span> <span class="search-result-import-path">hiro-graph-orm/lib/vertex/graph</span>',
        "function"
    ],
    [
        "hiro-graph-orm/lib/vertex~isvertex",
        "function/index.html#static-function-isVertex",
        '<span>isVertex</span> <span class="search-result-import-path">hiro-graph-orm/lib/vertex</span>',
        "function"
    ],
    [
        "hiro-graph-orm/lib/lucene~parselucene",
        "function/index.html#static-function-parseLucene",
        '<span>parseLucene</span> <span class="search-result-import-path">hiro-graph-orm/lib/lucene</span>',
        "function"
    ],
    [
        "hiro-graph-orm/lib/gremlin~querybuilder",
        "function/index.html#static-function-queryBuilder",
        '<span>queryBuilder</span> <span class="search-result-import-path">hiro-graph-orm/lib/gremlin</span>',
        "function"
    ],
    [
        "hiro-graph-orm/lib/schema/validate~validate",
        "function/index.html#static-function-validate",
        '<span>validate</span> <span class="search-result-import-path">hiro-graph-orm/lib/schema/validate</span>',
        "function"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~array",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Array",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~arraybuffer",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~boolean",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Boolean",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~dataview",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~DataView",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~date",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Date",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~error",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Error",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~evalerror",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~EvalError",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~float32array",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~float64array",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~function",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Function",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~generator",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Generator",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~generatorfunction",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~infinity",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Infinity",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~int16array",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~int32array",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~int8array",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~internalerror",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~InternalError",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~json",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~JSON",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~map",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Map",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~nan",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~NaN",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~number",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Number",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~object",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Object",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~promise",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Promise",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~proxy",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Proxy",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~rangeerror",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~RangeError",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~referenceerror",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~reflect",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Reflect",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~regexp",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~RegExp",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~set",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Set",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~string",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~String",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~symbol",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Symbol",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~syntaxerror",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~typeerror",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~TypeError",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~urierror",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~URIError",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~uint16array",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~uint32array",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~uint8array",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~weakmap",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~weakset",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~boolean",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~boolean",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~function",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~function",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~null",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~null",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~number",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~number",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~object",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~object",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~string",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~string",
        "external"
    ],
    [
        "builtinexternal/ecmascriptexternal.js~undefined",
        "external/index.html",
        "BuiltinExternal/ECMAScriptExternal.js~undefined",
        "external"
    ],
    [
        "builtinexternal/webapiexternal.js~audiocontext",
        "external/index.html",
        "BuiltinExternal/WebAPIExternal.js~AudioContext",
        "external"
    ],
    [
        "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
        "external/index.html",
        "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
        "external"
    ],
    [
        "builtinexternal/webapiexternal.js~documentfragment",
        "external/index.html",
        "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
        "external"
    ],
    [
        "builtinexternal/webapiexternal.js~element",
        "external/index.html",
        "BuiltinExternal/WebAPIExternal.js~Element",
        "external"
    ],
    [
        "builtinexternal/webapiexternal.js~event",
        "external/index.html",
        "BuiltinExternal/WebAPIExternal.js~Event",
        "external"
    ],
    [
        "builtinexternal/webapiexternal.js~node",
        "external/index.html",
        "BuiltinExternal/WebAPIExternal.js~Node",
        "external"
    ],
    [
        "builtinexternal/webapiexternal.js~nodelist",
        "external/index.html",
        "BuiltinExternal/WebAPIExternal.js~NodeList",
        "external"
    ],
    [
        "builtinexternal/webapiexternal.js~xmlhttprequest",
        "external/index.html",
        "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
        "external"
    ],
    [
        "src/bin/validate-schema-against-ontology.js",
        "file/src/bin/validate-schema-against-ontology.js.html",
        "src/bin/validate-schema-against-ontology.js",
        "file"
    ],
    [
        "src/codec/_number_utils.js",
        "file/src/codec/_number_utils.js.html",
        "src/codec/_number_utils.js",
        "file"
    ],
    [
        "src/codec/bool.js",
        "file/src/codec/bool.js.html",
        "src/codec/bool.js",
        "file"
    ],
    [
        "src/codec/enum.js",
        "file/src/codec/enum.js.html",
        "src/codec/enum.js",
        "file"
    ],
    [
        "src/codec/float.js",
        "file/src/codec/float.js.html",
        "src/codec/float.js",
        "file"
    ],
    [
        "src/codec/identity.js",
        "file/src/codec/identity.js.html",
        "src/codec/identity.js",
        "file"
    ],
    [
        "src/codec/index.js",
        "file/src/codec/index.js.html",
        "src/codec/index.js",
        "file"
    ],
    [
        "src/codec/int.js",
        "file/src/codec/int.js.html",
        "src/codec/int.js",
        "file"
    ],
    [
        "src/codec/iso8601.js",
        "file/src/codec/iso8601.js.html",
        "src/codec/iso8601.js",
        "file"
    ],
    [
        "src/codec/json.js",
        "file/src/codec/json.js.html",
        "src/codec/json.js",
        "file"
    ],
    [
        "src/codec/list.js",
        "file/src/codec/list.js.html",
        "src/codec/list.js",
        "file"
    ],
    [
        "src/codec/string.js",
        "file/src/codec/string.js.html",
        "src/codec/string.js",
        "file"
    ],
    [
        "src/codec/timestamp.js",
        "file/src/codec/timestamp.js.html",
        "src/codec/timestamp.js",
        "file"
    ],
    [
        "src/codec/uint.js",
        "file/src/codec/uint.js.html",
        "src/codec/uint.js",
        "file"
    ],
    [
        "src/context/context_entity.doc.js",
        "file/src/context/context_entity.doc.js.html",
        "src/context/context_entity.doc.js",
        "file"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#connect",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-connect",
        "src/context/context_entity.doc.js~Context$Entity#connect",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#create",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-create",
        "src/context/context_entity.doc.js~Context$Entity#create",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#decode",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-decode",
        "src/context/context_entity.doc.js~Context$Entity#decode",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#disconnect",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-disconnect",
        "src/context/context_entity.doc.js~Context$Entity#disconnect",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#encode",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-encode",
        "src/context/context_entity.doc.js~Context$Entity#encode",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#find",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-find",
        "src/context/context_entity.doc.js~Context$Entity#find",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#findbyid",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-findById",
        "src/context/context_entity.doc.js~Context$Entity#findById",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#findone",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-findOne",
        "src/context/context_entity.doc.js~Context$Entity#findOne",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#relationquery",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-relationQuery",
        "src/context/context_entity.doc.js~Context$Entity#relationQuery",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#replace",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-replace",
        "src/context/context_entity.doc.js~Context$Entity#replace",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#search",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-search",
        "src/context/context_entity.doc.js~Context$Entity#search",
        "method"
    ],
    [
        "src/context/context_entity.doc.js~context$entity#update",
        "class/src/context/context_entity.doc.js~Context$Entity.html#instance-method-update",
        "src/context/context_entity.doc.js~Context$Entity#update",
        "method"
    ],
    [
        "src/context/graph.js",
        "file/src/context/graph.js.html",
        "src/context/graph.js",
        "file"
    ],
    [
        "src/context/index.js",
        "file/src/context/index.js.html",
        "src/context/index.js",
        "file"
    ],
    [
        "src/context/index.js~context#constructor",
        "class/src/context/index.js~Context.html#instance-constructor-constructor",
        "src/context/index.js~Context#constructor",
        "method"
    ],
    [
        "src/context/index.js~context#delete",
        "class/src/context/index.js~Context.html#instance-method-delete",
        "src/context/index.js~Context#delete",
        "method"
    ],
    [
        "src/context/index.js~context#fetchcount",
        "class/src/context/index.js~Context.html#instance-method-fetchCount",
        "src/context/index.js~Context#fetchCount",
        "method"
    ],
    [
        "src/context/index.js~context#fetchids",
        "class/src/context/index.js~Context.html#instance-method-fetchIds",
        "src/context/index.js~Context#fetchIds",
        "method"
    ],
    [
        "src/context/index.js~context#fetchvertices",
        "class/src/context/index.js~Context.html#instance-method-fetchVertices",
        "src/context/index.js~Context#fetchVertices",
        "method"
    ],
    [
        "src/context/index.js~context#find",
        "class/src/context/index.js~Context.html#instance-method-find",
        "src/context/index.js~Context#find",
        "method"
    ],
    [
        "src/context/index.js~context#findbyid",
        "class/src/context/index.js~Context.html#instance-method-findById",
        "src/context/index.js~Context#findById",
        "method"
    ],
    [
        "src/context/index.js~context#findone",
        "class/src/context/index.js~Context.html#instance-method-findOne",
        "src/context/index.js~Context#findOne",
        "method"
    ],
    [
        "src/context/index.js~context#getconnection",
        "class/src/context/index.js~Context.html#instance-method-getConnection",
        "src/context/index.js~Context#getConnection",
        "method"
    ],
    [
        "src/context/index.js~context#getentity",
        "class/src/context/index.js~Context.html#instance-method-getEntity",
        "src/context/index.js~Context#getEntity",
        "method"
    ],
    [
        "src/context/index.js~context#gremlin",
        "class/src/context/index.js~Context.html#instance-method-gremlin",
        "src/context/index.js~Context#gremlin",
        "method"
    ],
    [
        "src/context/index.js~context#insert",
        "class/src/context/index.js~Context.html#instance-method-insert",
        "src/context/index.js~Context#insert",
        "method"
    ],
    [
        "src/context/index.js~context#insertraw",
        "class/src/context/index.js~Context.html#instance-method-insertRaw",
        "src/context/index.js~Context#insertRaw",
        "method"
    ],
    [
        "src/context/index.js~context#me",
        "class/src/context/index.js~Context.html#instance-method-me",
        "src/context/index.js~Context#me",
        "method"
    ],
    [
        "src/context/index.js~context#remove",
        "class/src/context/index.js~Context.html#instance-method-remove",
        "src/context/index.js~Context#remove",
        "method"
    ],
    [
        "src/context/index.js~context#search",
        "class/src/context/index.js~Context.html#instance-method-search",
        "src/context/index.js~Context#search",
        "method"
    ],
    [
        "src/context/index.js~context#setcache",
        "class/src/context/index.js~Context.html#instance-method-setCache",
        "src/context/index.js~Context#setCache",
        "method"
    ],
    [
        "src/context/relations.js",
        "file/src/context/relations.js.html",
        "src/context/relations.js",
        "file"
    ],
    [
        "src/gremlin/index.js",
        "file/src/gremlin/index.js.html",
        "src/gremlin/index.js",
        "file"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#addcomputedprop",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-addComputedProp",
        "src/gremlin/index.js~GremlinQueryBuilder#addComputedProp",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#addtempprop",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-addTempProp",
        "src/gremlin/index.js~GremlinQueryBuilder#addTempProp",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#append",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-append",
        "src/gremlin/index.js~GremlinQueryBuilder#append",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#as",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-as",
        "src/gremlin/index.js~GremlinQueryBuilder#as",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#back",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-back",
        "src/gremlin/index.js~GremlinQueryBuilder#back",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#both",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-both",
        "src/gremlin/index.js~GremlinQueryBuilder#both",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#bothe",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-bothE",
        "src/gremlin/index.js~GremlinQueryBuilder#bothE",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#bothv",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-bothV",
        "src/gremlin/index.js~GremlinQueryBuilder#bothV",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#constructor",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-constructor-constructor",
        "src/gremlin/index.js~GremlinQueryBuilder#constructor",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#copysplit",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-copySplit",
        "src/gremlin/index.js~GremlinQueryBuilder#copySplit",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#count",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-count",
        "src/gremlin/index.js~GremlinQueryBuilder#count",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#dedup",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-dedup",
        "src/gremlin/index.js~GremlinQueryBuilder#dedup",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#execute",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-execute",
        "src/gremlin/index.js~GremlinQueryBuilder#execute",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#executeincontext",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-executeInContext",
        "src/gremlin/index.js~GremlinQueryBuilder#executeInContext",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#filter",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-filter",
        "src/gremlin/index.js~GremlinQueryBuilder#filter",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#getproperty",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-getProperty",
        "src/gremlin/index.js~GremlinQueryBuilder#getProperty",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#groupby",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-groupBy",
        "src/gremlin/index.js~GremlinQueryBuilder#groupBy",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#groupcount",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-groupCount",
        "src/gremlin/index.js~GremlinQueryBuilder#groupCount",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#has",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-has",
        "src/gremlin/index.js~GremlinQueryBuilder#has",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#hasnot",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-hasNot",
        "src/gremlin/index.js~GremlinQueryBuilder#hasNot",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#in",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-in",
        "src/gremlin/index.js~GremlinQueryBuilder#in",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#ine",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-inE",
        "src/gremlin/index.js~GremlinQueryBuilder#inE",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#inv",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-inV",
        "src/gremlin/index.js~GremlinQueryBuilder#inV",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#limit",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-limit",
        "src/gremlin/index.js~GremlinQueryBuilder#limit",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#or",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-or",
        "src/gremlin/index.js~GremlinQueryBuilder#or",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#order",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-order",
        "src/gremlin/index.js~GremlinQueryBuilder#order",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#out",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-out",
        "src/gremlin/index.js~GremlinQueryBuilder#out",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#oute",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-outE",
        "src/gremlin/index.js~GremlinQueryBuilder#outE",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#outv",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-outV",
        "src/gremlin/index.js~GremlinQueryBuilder#outV",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#raw",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-raw",
        "src/gremlin/index.js~GremlinQueryBuilder#raw",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#relation",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-relation",
        "src/gremlin/index.js~GremlinQueryBuilder#relation",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#shuffle",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-shuffle",
        "src/gremlin/index.js~GremlinQueryBuilder#shuffle",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#tostring",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-toString",
        "src/gremlin/index.js~GremlinQueryBuilder#toString",
        "method"
    ],
    [
        "src/gremlin/index.js~gremlinquerybuilder#transform",
        "class/src/gremlin/index.js~GremlinQueryBuilder.html#instance-method-transform",
        "src/gremlin/index.js~GremlinQueryBuilder#transform",
        "method"
    ],
    ["src/index.js", "file/src/index.js.html", "src/index.js", "file"],
    [
        "src/lucene/index.js",
        "file/src/lucene/index.js.html",
        "src/lucene/index.js",
        "file"
    ],
    [
        "src/schema/entity.js",
        "file/src/schema/entity.js.html",
        "src/schema/entity.js",
        "file"
    ],
    [
        "src/schema/index.js",
        "file/src/schema/index.js.html",
        "src/schema/index.js",
        "file"
    ],
    [
        "src/schema/index.js~schema#constructor",
        "class/src/schema/index.js~Schema.html#instance-constructor-constructor",
        "src/schema/index.js~Schema#constructor",
        "method"
    ],
    [
        "src/schema/index.js~schema#define",
        "class/src/schema/index.js~Schema.html#instance-method-define",
        "src/schema/index.js~Schema#define",
        "method"
    ],
    [
        "src/schema/index.js~schema#get",
        "class/src/schema/index.js~Schema.html#instance-method-get",
        "src/schema/index.js~Schema#get",
        "method"
    ],
    [
        "src/schema/validate.js",
        "file/src/schema/validate.js.html",
        "src/schema/validate.js",
        "file"
    ],
    [
        "src/types/externals.js",
        "file/src/types/externals.js.html",
        "src/types/externals.js",
        "file"
    ],
    [
        "src/types/externals.js~connection",
        "external/index.html",
        "src/types/externals.js~Connection",
        "external"
    ],
    [
        "src/types/typedefs.js",
        "file/src/types/typedefs.js.html",
        "src/types/typedefs.js",
        "file"
    ],
    [
        "src/types/typedefs.js~codec",
        "typedef/index.html#static-typedef-Codec",
        "src/types/typedefs.js~Codec",
        "typedef"
    ],
    [
        "src/types/typedefs.js~gremlinbranch",
        "typedef/index.html#static-typedef-GremlinBranch",
        "src/types/typedefs.js~GremlinBranch",
        "typedef"
    ],
    [
        "src/types/typedefs.js~lucenequery",
        "typedef/index.html#static-typedef-LuceneQuery",
        "src/types/typedefs.js~LuceneQuery",
        "typedef"
    ],
    [
        "src/types/typedefs.js~oneormorevertices",
        "typedef/index.html#static-typedef-OneOrMoreVertices",
        "src/types/typedefs.js~OneOrMoreVertices",
        "typedef"
    ],
    [
        "src/utils/index.js",
        "file/src/utils/index.js.html",
        "src/utils/index.js",
        "file"
    ],
    [
        "src/vertex/graph.js",
        "file/src/vertex/graph.js.html",
        "src/vertex/graph.js",
        "file"
    ],
    [
        "src/vertex/graph.js~graphvertex#canwrite",
        "class/src/vertex/graph.js~GraphVertex.html#instance-method-canWrite",
        "src/vertex/graph.js~GraphVertex#canWrite",
        "method"
    ],
    [
        "src/vertex/graph.js~graphvertex#connect",
        "class/src/vertex/graph.js~GraphVertex.html#instance-method-connect",
        "src/vertex/graph.js~GraphVertex#connect",
        "method"
    ],
    [
        "src/vertex/graph.js~graphvertex#delete",
        "class/src/vertex/graph.js~GraphVertex.html#instance-method-delete",
        "src/vertex/graph.js~GraphVertex#delete",
        "method"
    ],
    [
        "src/vertex/graph.js~graphvertex#disconnect",
        "class/src/vertex/graph.js~GraphVertex.html#instance-method-disconnect",
        "src/vertex/graph.js~GraphVertex#disconnect",
        "method"
    ],
    [
        "src/vertex/graph.js~graphvertex#fetchcount",
        "class/src/vertex/graph.js~GraphVertex.html#instance-method-fetchCount",
        "src/vertex/graph.js~GraphVertex#fetchCount",
        "method"
    ],
    [
        "src/vertex/graph.js~graphvertex#fetchids",
        "class/src/vertex/graph.js~GraphVertex.html#instance-method-fetchIds",
        "src/vertex/graph.js~GraphVertex#fetchIds",
        "method"
    ],
    [
        "src/vertex/graph.js~graphvertex#fetchvertices",
        "class/src/vertex/graph.js~GraphVertex.html#instance-method-fetchVertices",
        "src/vertex/graph.js~GraphVertex#fetchVertices",
        "method"
    ],
    [
        "src/vertex/graph.js~graphvertex#getvertices",
        "class/src/vertex/graph.js~GraphVertex.html#instance-method-getVertices",
        "src/vertex/graph.js~GraphVertex#getVertices",
        "method"
    ],
    [
        "src/vertex/graph.js~graphvertex#save",
        "class/src/vertex/graph.js~GraphVertex.html#instance-method-save",
        "src/vertex/graph.js~GraphVertex#save",
        "method"
    ],
    [
        "src/vertex/index.js",
        "file/src/vertex/index.js.html",
        "src/vertex/index.js",
        "file"
    ],
    [
        "src/vertex/index.js~vertex#constructor",
        "class/src/vertex/index.js~Vertex.html#instance-constructor-constructor",
        "src/vertex/index.js~Vertex#constructor",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#get",
        "class/src/vertex/index.js~Vertex.html#instance-method-get",
        "src/vertex/index.js~Vertex#get",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#getcount",
        "class/src/vertex/index.js~Vertex.html#instance-method-getCount",
        "src/vertex/index.js~Vertex#getCount",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#getfree",
        "class/src/vertex/index.js~Vertex.html#instance-method-getFree",
        "src/vertex/index.js~Vertex#getFree",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#getids",
        "class/src/vertex/index.js~Vertex.html#instance-method-getIds",
        "src/vertex/index.js~Vertex#getIds",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#plain",
        "class/src/vertex/index.js~Vertex.html#instance-method-plain",
        "src/vertex/index.js~Vertex#plain",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#set",
        "class/src/vertex/index.js~Vertex.html#instance-method-set",
        "src/vertex/index.js~Vertex#set",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#setcount",
        "class/src/vertex/index.js~Vertex.html#instance-method-setCount",
        "src/vertex/index.js~Vertex#setCount",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#setids",
        "class/src/vertex/index.js~Vertex.html#instance-method-setIds",
        "src/vertex/index.js~Vertex#setIds",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#setvertices",
        "class/src/vertex/index.js~Vertex.html#instance-method-setVertices",
        "src/vertex/index.js~Vertex#setVertices",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#tojson",
        "class/src/vertex/index.js~Vertex.html#instance-method-toJSON",
        "src/vertex/index.js~Vertex#toJSON",
        "method"
    ],
    [
        "src/vertex/index.js~vertex#type",
        "class/src/vertex/index.js~Vertex.html#instance-method-type",
        "src/vertex/index.js~Vertex#type",
        "method"
    ]
];
